# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = network_sniff
DESTDIR = ./Release
CONFIG += release
DEFINES += HAVE_REMOTE WPCAP
LIBS += -L"." \
    -lws2_32 \
    -lwpcap
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(network_sniff.pri)
